# Используем официальный PHP образ
FROM php:8.4-cli

# Устанавливаем расширения PHP
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Устанавливаем Xdebug (если нужен)
RUN pecl install xdebug && docker-php-ext-enable xdebug

# Устанавливаем рабочую директорию в контейнере
WORKDIR /var/www

# Копируем текущий код (на всякий случай, если не используем монтирование)
# COPY ./src /var/www

# Указываем команду по умолчанию для запуска PHP Development Server
CMD ["php", "-S", "0.0.0.0:8000", "-t", "public"]
