# Use root/example as user/password credentials
version: '3.1'

services:

  pv211.test.mongo:
    build:
      dockerfile: ./Dockerfile_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


  pv211.test.mongo-express:
    image: mongo-express
    ports:
      - 8001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@pv211.test.mongo:27017/
      ME_CONFIG_BASICAUTH: false
